### ISSUE TITLE
new hg backups are failing

### ISSUE THREAD

**Issue by ewdurbin** [python/psf-salt#474]
From cron to infrastructure-staff:

> Warning: Identity file /etc/backup/.ssh/id_rsa_hg-mercurial-static not accessible: No such file or directory.
[root@backup.sfo1.psf.io](mailto:root@backup.sfo1.psf.io): Permission denied (publickey).

and

> Warning: Identity file /etc/backup/.ssh/id_rsa_hg-svn-config not accessible: No such file or directory.
[root@backup.sfo1.psf.io](mailto:root@backup.sfo1.psf.io): Permission denied (publickey).

It looks like this is because we infer that a given backup config has an individual backup key when [templating the remote command](https://github.com/python/psf-salt/blob/37e194a5272ac259b7d756de37fb912a54f2d944/salt/backup/client/init.sls#L42-L44).

**Comment by JacobCoffee** [comment]
Investigating... Keys are not being made for the two new entries :(
```
root@hg:~# ls /etc/backup/.ssh
id_rsa_python-hg
```
from
```
{{ backup }}-ssh-key:
  file.managed:
    - name: /etc/backup/.ssh/id_rsa_{{ backup }}
    - contents_pillar: backup-secret:directories:{{ backup }}:ssh_key
    - user: {{ config['user'] }}
    - mode: "0600"
    - show_diff: False 
```
