### ISSUE TITLE
Docs: Add section on managing/adding backups

### ISSUE THREAD

**Issue by JacobCoffee** [python/psf-salt#475]
## What 

When adding new backup files/directories, we will need to add related keys for this. This and other things (like SSH key changes when hosts upgrade/change) should be documented
___

Keys are not being made for the two new entries :(
```
root@hg:~# ls /etc/backup/.ssh
id_rsa_python-hg
```
from
```
{{ backup }}-ssh-key:
  file.managed:
    - name: /etc/backup/.ssh/id_rsa_{{ backup }}
    - contents_pillar: backup-secret:directories:{{ backup }}:ssh_key
    - user: {{ config['user'] }}
    - mode: "0600"
    - show_diff: False 
```
probably due to missing pillar data in the secrets file for backup

_Originally posted by @JacobCoffee in https://github.com/python/psf-salt/issues/474#issuecomment-2297259859_
